// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lszfxsormiehszujdajf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzemZ4c29ybWllaHN6dWpkYWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjE3NzksImV4cCI6MjA1NjU5Nzc3OX0._iGbLqajeknBF2actb5ptNoQb3bV7yvsafY_j4WosAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);